// Mocks generated by Mockito 5.4.6 from annotations
// in sss/test/core/services/update_service_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i7;

import 'package:mockito/mockito.dart' as _i1;
import 'package:sss/core/config/app_role.dart' as _i13;
import 'package:sss/core/configuration/domain/entities/app_configuration.dart'
    as _i2;
import 'package:sss/core/configuration/domain/repositories/configuration_repository.dart'
    as _i15;
import 'package:sss/core/database/daos/branches_dao.dart' as _i6;
import 'package:sss/core/database/daos/tenants_dao.dart' as _i4;
import 'package:sss/core/database/daos/tiers_dao.dart' as _i5;
import 'package:sss/core/models/terminal_info.dart' as _i14;
import 'package:sss/core/models/update_info.dart' as _i10;
import 'package:sss/features/auth/domain/entities/branch.dart' as _i11;
import 'package:sss/features/auth/domain/entities/tenant.dart' as _i8;
import 'package:sss/features/auth/domain/entities/tier.dart' as _i9;
import 'package:sss/features/auth/domain/services/tenant_service.dart' as _i3;
import 'package:sss/features/warehouse/domain/entities/warehouse.dart' as _i12;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeAppConfiguration_0 extends _i1.SmartFake
    implements _i2.AppConfiguration {
  _FakeAppConfiguration_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [TenantService].
///
/// See the documentation for Mockito's code generation for more information.
class MockTenantService extends _i1.Mock implements _i3.TenantService {
  MockTenantService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get isMaintenanceMode =>
      (super.noSuchMethod(
            Invocation.getter(#isMaintenanceMode),
            returnValue: false,
          )
          as bool);

  @override
  void setTenantsDao(_i4.TenantsDao? dao) => super.noSuchMethod(
    Invocation.method(#setTenantsDao, [dao]),
    returnValueForMissingStub: null,
  );

  @override
  void setTiersDao(_i5.TiersDao? dao) => super.noSuchMethod(
    Invocation.method(#setTiersDao, [dao]),
    returnValueForMissingStub: null,
  );

  @override
  void setBranchesDao(_i6.BranchesDao? dao) => super.noSuchMethod(
    Invocation.method(#setBranchesDao, [dao]),
    returnValueForMissingStub: null,
  );

  @override
  _i7.Future<void> initialize() =>
      (super.noSuchMethod(
            Invocation.method(#initialize, []),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  List<_i8.Tenant> getTenants() =>
      (super.noSuchMethod(
            Invocation.method(#getTenants, []),
            returnValue: <_i8.Tenant>[],
          )
          as List<_i8.Tenant>);

  @override
  _i7.Future<void> addTenant(_i8.Tenant? tenant) =>
      (super.noSuchMethod(
            Invocation.method(#addTenant, [tenant]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> updateTenant(_i8.Tenant? updatedTenant) =>
      (super.noSuchMethod(
            Invocation.method(#updateTenant, [updatedTenant]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> syncTenantToCloud(_i8.Tenant? tenant) =>
      (super.noSuchMethod(
            Invocation.method(#syncTenantToCloud, [tenant]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> deleteTenant(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteTenant, [id]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  List<_i9.Tier> getTiers() =>
      (super.noSuchMethod(
            Invocation.method(#getTiers, []),
            returnValue: <_i9.Tier>[],
          )
          as List<_i9.Tier>);

  @override
  _i9.Tier? getTierById(String? id) =>
      (super.noSuchMethod(Invocation.method(#getTierById, [id])) as _i9.Tier?);

  @override
  _i7.Future<void> addTier(_i9.Tier? tier) =>
      (super.noSuchMethod(
            Invocation.method(#addTier, [tier]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> updateTier(_i9.Tier? tier) =>
      (super.noSuchMethod(
            Invocation.method(#updateTier, [tier]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> deleteTier(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteTier, [id]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> syncTierToCloud(_i9.Tier? tier) =>
      (super.noSuchMethod(
            Invocation.method(#syncTierToCloud, [tier]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> pullTiersFromCloud() =>
      (super.noSuchMethod(
            Invocation.method(#pullTiersFromCloud, []),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> pullTenantsFromCloud() =>
      (super.noSuchMethod(
            Invocation.method(#pullTenantsFromCloud, []),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  Map<String, dynamic> getStats() =>
      (super.noSuchMethod(
            Invocation.method(#getStats, []),
            returnValue: <String, dynamic>{},
          )
          as Map<String, dynamic>);

  @override
  bool canAccessFeature(String? tenantId, String? feature) =>
      (super.noSuchMethod(
            Invocation.method(#canAccessFeature, [tenantId, feature]),
            returnValue: false,
          )
          as bool);

  @override
  void setTenantMaintenanceMode(String? tenantId, bool? enabled) =>
      super.noSuchMethod(
        Invocation.method(#setTenantMaintenanceMode, [tenantId, enabled]),
        returnValueForMissingStub: null,
      );

  @override
  void setMaintenanceMode(bool? enabled) => super.noSuchMethod(
    Invocation.method(#setMaintenanceMode, [enabled]),
    returnValueForMissingStub: null,
  );

  @override
  void setModuleMaintenance(String? module, bool? enabled) =>
      super.noSuchMethod(
        Invocation.method(#setModuleMaintenance, [module, enabled]),
        returnValueForMissingStub: null,
      );

  @override
  bool isModuleUnderMaintenance(String? module) =>
      (super.noSuchMethod(
            Invocation.method(#isModuleUnderMaintenance, [module]),
            returnValue: false,
          )
          as bool);

  @override
  _i7.Future<void> syncGlobalConfig() =>
      (super.noSuchMethod(
            Invocation.method(#syncGlobalConfig, []),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> pushUpdateManifest(_i10.UpdateInfo? updateInfo) =>
      (super.noSuchMethod(
            Invocation.method(#pushUpdateManifest, [updateInfo]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<List<_i10.UpdateInfo>> getLatestUpdateManifests() =>
      (super.noSuchMethod(
            Invocation.method(#getLatestUpdateManifests, []),
            returnValue: _i7.Future<List<_i10.UpdateInfo>>.value(
              <_i10.UpdateInfo>[],
            ),
          )
          as _i7.Future<List<_i10.UpdateInfo>>);

  @override
  _i7.Future<_i10.UpdateInfo?> getLatestUpdateManifest() =>
      (super.noSuchMethod(
            Invocation.method(#getLatestUpdateManifest, []),
            returnValue: _i7.Future<_i10.UpdateInfo?>.value(),
          )
          as _i7.Future<_i10.UpdateInfo?>);

  @override
  bool isTenantImmune(String? tenantId, {String? fallbackTierId}) =>
      (super.noSuchMethod(
            Invocation.method(
              #isTenantImmune,
              [tenantId],
              {#fallbackTierId: fallbackTierId},
            ),
            returnValue: false,
          )
          as bool);

  @override
  bool isTenantAllowedUpdates(String? tenantId) =>
      (super.noSuchMethod(
            Invocation.method(#isTenantAllowedUpdates, [tenantId]),
            returnValue: false,
          )
          as bool);

  @override
  bool canAccessSystem(
    String? tenantId, {
    bool? isSuperAdmin = false,
    String? fallbackTierId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #canAccessSystem,
              [tenantId],
              {#isSuperAdmin: isSuperAdmin, #fallbackTierId: fallbackTierId},
            ),
            returnValue: false,
          )
          as bool);

  @override
  bool isTenantEnabled(String? tenantId) =>
      (super.noSuchMethod(
            Invocation.method(#isTenantEnabled, [tenantId]),
            returnValue: false,
          )
          as bool);

  @override
  _i8.Tenant? login(String? email, String? password) =>
      (super.noSuchMethod(Invocation.method(#login, [email, password]))
          as _i8.Tenant?);

  @override
  bool isSuperAdmin(String? tenantId) =>
      (super.noSuchMethod(
            Invocation.method(#isSuperAdmin, [tenantId]),
            returnValue: false,
          )
          as bool);

  @override
  void completeLogin(String? tenantId) => super.noSuchMethod(
    Invocation.method(#completeLogin, [tenantId]),
    returnValueForMissingStub: null,
  );

  @override
  bool isFirstLogin(String? tenantId) =>
      (super.noSuchMethod(
            Invocation.method(#isFirstLogin, [tenantId]),
            returnValue: false,
          )
          as bool);

  @override
  void resetForTesting() => super.noSuchMethod(
    Invocation.method(#resetForTesting, []),
    returnValueForMissingStub: null,
  );

  @override
  _i7.Future<List<_i11.Branch>> getBranchesForTenant(String? tenantId) =>
      (super.noSuchMethod(
            Invocation.method(#getBranchesForTenant, [tenantId]),
            returnValue: _i7.Future<List<_i11.Branch>>.value(<_i11.Branch>[]),
          )
          as _i7.Future<List<_i11.Branch>>);

  @override
  _i7.Future<void> updateBranch(_i11.Branch? branch) =>
      (super.noSuchMethod(
            Invocation.method(#updateBranch, [branch]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> addBranch(_i11.Branch? branch) =>
      (super.noSuchMethod(
            Invocation.method(#addBranch, [branch]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> syncWarehouseToCloud(_i12.Warehouse? warehouse) =>
      (super.noSuchMethod(
            Invocation.method(#syncWarehouseToCloud, [warehouse]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<Map<String, dynamic>?> cloudLogin(
    String? identifier,
    String? password,
    _i13.AppRole? role,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#cloudLogin, [identifier, password, role]),
            returnValue: _i7.Future<Map<String, dynamic>?>.value(),
          )
          as _i7.Future<Map<String, dynamic>?>);

  @override
  _i7.Future<void> deleteBranch(String? branchId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteBranch, [branchId]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<_i11.Branch?> getBranchById(String? branchId) =>
      (super.noSuchMethod(
            Invocation.method(#getBranchById, [branchId]),
            returnValue: _i7.Future<_i11.Branch?>.value(),
          )
          as _i7.Future<_i11.Branch?>);

  @override
  _i7.Future<_i8.Tenant?> getTenantForBranch(String? branchId) =>
      (super.noSuchMethod(
            Invocation.method(#getTenantForBranch, [branchId]),
            returnValue: _i7.Future<_i8.Tenant?>.value(),
          )
          as _i7.Future<_i8.Tenant?>);

  @override
  _i7.Future<Map<String, dynamic>?> localLogin(
    String? identifier,
    String? password,
    _i13.AppRole? role,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#localLogin, [identifier, password, role]),
            returnValue: _i7.Future<Map<String, dynamic>?>.value(),
          )
          as _i7.Future<Map<String, dynamic>?>);

  @override
  _i7.Future<void> syncTenantWithCloud(String? tenantId) =>
      (super.noSuchMethod(
            Invocation.method(#syncTenantWithCloud, [tenantId]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> reportTerminalStatus(_i14.TerminalInfo? terminalInfo) =>
      (super.noSuchMethod(
            Invocation.method(#reportTerminalStatus, [terminalInfo]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<List<_i14.TerminalInfo>> getAllTerminals() =>
      (super.noSuchMethod(
            Invocation.method(#getAllTerminals, []),
            returnValue: _i7.Future<List<_i14.TerminalInfo>>.value(
              <_i14.TerminalInfo>[],
            ),
          )
          as _i7.Future<List<_i14.TerminalInfo>>);
}

/// A class which mocks [ConfigurationRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockConfigurationRepository extends _i1.Mock
    implements _i15.ConfigurationRepository {
  MockConfigurationRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i7.Future<_i2.AppConfiguration> getConfiguration() =>
      (super.noSuchMethod(
            Invocation.method(#getConfiguration, []),
            returnValue: _i7.Future<_i2.AppConfiguration>.value(
              _FakeAppConfiguration_0(
                this,
                Invocation.method(#getConfiguration, []),
              ),
            ),
          )
          as _i7.Future<_i2.AppConfiguration>);

  @override
  _i7.Future<void> saveConfiguration(_i2.AppConfiguration? configuration) =>
      (super.noSuchMethod(
            Invocation.method(#saveConfiguration, [configuration]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);
}
