// Mocks generated by Mockito 5.4.6 from annotations
// in sss/test/features/products/product_repository_source_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;

import 'package:http/http.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:sss/core/configuration/domain/entities/app_configuration.dart'
    as _i4;
import 'package:sss/core/configuration/domain/repositories/configuration_repository.dart'
    as _i11;
import 'package:sss/features/auth/domain/entities/tenant.dart' as _i3;
import 'package:sss/features/auth/domain/repositories/auth_repository.dart'
    as _i10;
import 'package:sss/features/products/data/datasources/local_product_datasource.dart'
    as _i5;
import 'package:sss/features/products/data/datasources/product_remote_datasource.dart'
    as _i8;
import 'package:sss/features/products/data/datasources/sap_product_datasource.dart'
    as _i9;
import 'package:sss/features/products/data/models/product_model.dart' as _i7;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeClient_0 extends _i1.SmartFake implements _i2.Client {
  _FakeClient_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeTenant_1 extends _i1.SmartFake implements _i3.Tenant {
  _FakeTenant_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeAppConfiguration_2 extends _i1.SmartFake
    implements _i4.AppConfiguration {
  _FakeAppConfiguration_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [LocalProductDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockLocalProductDataSource extends _i1.Mock
    implements _i5.LocalProductDataSource {
  MockLocalProductDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<List<_i7.ProductModel>> fetchProducts({String? tenantId}) =>
      (super.noSuchMethod(
            Invocation.method(#fetchProducts, [], {#tenantId: tenantId}),
            returnValue: _i6.Future<List<_i7.ProductModel>>.value(
              <_i7.ProductModel>[],
            ),
          )
          as _i6.Future<List<_i7.ProductModel>>);

  @override
  _i6.Future<_i7.ProductModel?> getProductById(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getProductById, [id]),
            returnValue: _i6.Future<_i7.ProductModel?>.value(),
          )
          as _i6.Future<_i7.ProductModel?>);

  @override
  _i6.Future<void> addProduct(_i7.ProductModel? product) =>
      (super.noSuchMethod(
            Invocation.method(#addProduct, [product]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> updateProduct(_i7.ProductModel? product) =>
      (super.noSuchMethod(
            Invocation.method(#updateProduct, [product]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> deleteProduct(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteProduct, [id]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<int?> getCustomerPriceListNum() =>
      (super.noSuchMethod(
            Invocation.method(#getCustomerPriceListNum, []),
            returnValue: _i6.Future<int?>.value(),
          )
          as _i6.Future<int?>);

  @override
  _i6.Future<Map<String, double>> getCustomerSpecialPrices() =>
      (super.noSuchMethod(
            Invocation.method(#getCustomerSpecialPrices, []),
            returnValue: _i6.Future<Map<String, double>>.value(
              <String, double>{},
            ),
          )
          as _i6.Future<Map<String, double>>);

  @override
  void clearCache() => super.noSuchMethod(
    Invocation.method(#clearCache, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [ProductRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockProductRemoteDataSource extends _i1.Mock
    implements _i8.ProductRemoteDataSource {
  MockProductRemoteDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.Client get client =>
      (super.noSuchMethod(
            Invocation.getter(#client),
            returnValue: _FakeClient_0(this, Invocation.getter(#client)),
          )
          as _i2.Client);

  @override
  _i6.Future<List<_i7.ProductModel>> fetchProducts({String? tenantId}) =>
      (super.noSuchMethod(
            Invocation.method(#fetchProducts, [], {#tenantId: tenantId}),
            returnValue: _i6.Future<List<_i7.ProductModel>>.value(
              <_i7.ProductModel>[],
            ),
          )
          as _i6.Future<List<_i7.ProductModel>>);

  @override
  _i6.Future<_i7.ProductModel?> getProductById(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getProductById, [id]),
            returnValue: _i6.Future<_i7.ProductModel?>.value(),
          )
          as _i6.Future<_i7.ProductModel?>);

  @override
  _i6.Future<void> addProduct(_i7.ProductModel? product) =>
      (super.noSuchMethod(
            Invocation.method(#addProduct, [product]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> updateProduct(_i7.ProductModel? product) =>
      (super.noSuchMethod(
            Invocation.method(#updateProduct, [product]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> deleteProduct(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteProduct, [id]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<int?> getCustomerPriceListNum() =>
      (super.noSuchMethod(
            Invocation.method(#getCustomerPriceListNum, []),
            returnValue: _i6.Future<int?>.value(),
          )
          as _i6.Future<int?>);

  @override
  _i6.Future<Map<String, double>> getCustomerSpecialPrices() =>
      (super.noSuchMethod(
            Invocation.method(#getCustomerSpecialPrices, []),
            returnValue: _i6.Future<Map<String, double>>.value(
              <String, double>{},
            ),
          )
          as _i6.Future<Map<String, double>>);

  @override
  void clearCache() => super.noSuchMethod(
    Invocation.method(#clearCache, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [SapProductDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockSapProductDataSource extends _i1.Mock
    implements _i9.SapProductDataSource {
  MockSapProductDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.Client get client =>
      (super.noSuchMethod(
            Invocation.getter(#client),
            returnValue: _FakeClient_0(this, Invocation.getter(#client)),
          )
          as _i2.Client);

  @override
  void updateLocalImage(String? productId, String? imageUrl) =>
      super.noSuchMethod(
        Invocation.method(#updateLocalImage, [productId, imageUrl]),
        returnValueForMissingStub: null,
      );

  @override
  _i6.Future<int?> getCustomerPriceListNum() =>
      (super.noSuchMethod(
            Invocation.method(#getCustomerPriceListNum, []),
            returnValue: _i6.Future<int?>.value(),
          )
          as _i6.Future<int?>);

  @override
  _i6.Future<Map<String, double>> getCustomerSpecialPrices() =>
      (super.noSuchMethod(
            Invocation.method(#getCustomerSpecialPrices, []),
            returnValue: _i6.Future<Map<String, double>>.value(
              <String, double>{},
            ),
          )
          as _i6.Future<Map<String, double>>);

  @override
  _i6.Future<List<_i7.ProductModel>> fetchProducts({String? tenantId}) =>
      (super.noSuchMethod(
            Invocation.method(#fetchProducts, [], {#tenantId: tenantId}),
            returnValue: _i6.Future<List<_i7.ProductModel>>.value(
              <_i7.ProductModel>[],
            ),
          )
          as _i6.Future<List<_i7.ProductModel>>);

  @override
  _i6.Future<_i7.ProductModel?> getProductById(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getProductById, [id]),
            returnValue: _i6.Future<_i7.ProductModel?>.value(),
          )
          as _i6.Future<_i7.ProductModel?>);

  @override
  _i6.Future<void> addProduct(_i7.ProductModel? product) =>
      (super.noSuchMethod(
            Invocation.method(#addProduct, [product]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> updateProduct(_i7.ProductModel? product) =>
      (super.noSuchMethod(
            Invocation.method(#updateProduct, [product]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> deleteProduct(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteProduct, [id]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  void clearCache() => super.noSuchMethod(
    Invocation.method(#clearCache, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [AuthRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthRepository extends _i1.Mock implements _i10.AuthRepository {
  MockAuthRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<_i3.Tenant> login(String? username, String? password) =>
      (super.noSuchMethod(
            Invocation.method(#login, [username, password]),
            returnValue: _i6.Future<_i3.Tenant>.value(
              _FakeTenant_1(
                this,
                Invocation.method(#login, [username, password]),
              ),
            ),
          )
          as _i6.Future<_i3.Tenant>);

  @override
  _i6.Future<void> logout() =>
      (super.noSuchMethod(
            Invocation.method(#logout, []),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> saveSession(_i3.Tenant? tenant) =>
      (super.noSuchMethod(
            Invocation.method(#saveSession, [tenant]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<_i3.Tenant?> getCurrentTenant() =>
      (super.noSuchMethod(
            Invocation.method(#getCurrentTenant, []),
            returnValue: _i6.Future<_i3.Tenant?>.value(),
          )
          as _i6.Future<_i3.Tenant?>);
}

/// A class which mocks [ConfigurationRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockConfigurationRepository extends _i1.Mock
    implements _i11.ConfigurationRepository {
  MockConfigurationRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<_i4.AppConfiguration> getConfiguration() =>
      (super.noSuchMethod(
            Invocation.method(#getConfiguration, []),
            returnValue: _i6.Future<_i4.AppConfiguration>.value(
              _FakeAppConfiguration_2(
                this,
                Invocation.method(#getConfiguration, []),
              ),
            ),
          )
          as _i6.Future<_i4.AppConfiguration>);

  @override
  _i6.Future<void> saveConfiguration(_i4.AppConfiguration? configuration) =>
      (super.noSuchMethod(
            Invocation.method(#saveConfiguration, [configuration]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);
}
