// Mocks generated by Mockito 5.4.6 from annotations
// in sss/test/features/products/product_isolation_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i7;

import 'package:drift/drift.dart' as _i5;
import 'package:drift/src/runtime/executor/stream_queries.dart' as _i6;
import 'package:http/http.dart' as _i3;
import 'package:sss/core/configuration/domain/entities/app_configuration.dart'
    as _i8;
import 'package:sss/core/configuration/domain/repositories/configuration_repository.dart'
    as _i15;
import 'package:sss/core/database/app_database.dart' as _i4;
import 'package:sss/core/database/daos/products_dao.dart' as _i13;
import 'package:sss/features/auth/domain/entities/tenant.dart' as _i2;
import 'package:sss/features/auth/domain/repositories/auth_repository.dart'
    as _i9;
import 'package:sss/features/products/data/datasources/product_remote_datasource.dart'
    as _i10;
import 'package:sss/features/products/data/datasources/sap_product_datasource.dart'
    as _i12;
import 'package:sss/features/products/data/models/product_model.dart'
    as _i11;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i14;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeTenant_0 extends _i1.SmartFake implements _i2.Tenant {
  _FakeTenant_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeClient_1 extends _i1.SmartFake implements _i3.Client {
  _FakeClient_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeAppDatabase_2 extends _i1.SmartFake implements _i4.AppDatabase {
  _FakeAppDatabase_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeDatabaseConnection_3 extends _i1.SmartFake
    implements _i5.DatabaseConnection {
  _FakeDatabaseConnection_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeDriftDatabaseOptions_4 extends _i1.SmartFake
    implements _i5.DriftDatabaseOptions {
  _FakeDriftDatabaseOptions_4(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeQueryExecutor_5 extends _i1.SmartFake implements _i5.QueryExecutor {
  _FakeQueryExecutor_5(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeStreamQueryStore_6 extends _i1.SmartFake
    implements _i6.StreamQueryStore {
  _FakeStreamQueryStore_6(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeDatabaseConnectionUser_7 extends _i1.SmartFake
    implements _i5.DatabaseConnectionUser {
  _FakeDatabaseConnectionUser_7(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _Fake$ProductsTable_8 extends _i1.SmartFake
    implements _i4.$ProductsTable {
  _Fake$ProductsTable_8(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeFuture_9<T1> extends _i1.SmartFake implements _i7.Future<T1> {
  _FakeFuture_9(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeInsertStatement_10<T1 extends _i5.Table, D1> extends _i1.SmartFake
    implements _i5.InsertStatement<T1, D1> {
  _FakeInsertStatement_10(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeUpdateStatement_11<T extends _i5.Table, D> extends _i1.SmartFake
    implements _i5.UpdateStatement<T, D> {
  _FakeUpdateStatement_11(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeSimpleSelectStatement_12<T1 extends _i5.HasResultSet, D>
    extends _i1.SmartFake
    implements _i5.SimpleSelectStatement<T1, D> {
  _FakeSimpleSelectStatement_12(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeJoinedSelectStatement_13<FirstT extends _i5.HasResultSet, FirstD>
    extends _i1.SmartFake
    implements _i5.JoinedSelectStatement<FirstT, FirstD> {
  _FakeJoinedSelectStatement_13(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeBaseSelectStatement_14<Row> extends _i1.SmartFake
    implements _i5.BaseSelectStatement<Row> {
  _FakeBaseSelectStatement_14(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeDeleteStatement_15<T1 extends _i5.Table, D1> extends _i1.SmartFake
    implements _i5.DeleteStatement<T1, D1> {
  _FakeDeleteStatement_15(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeSelectable_16<T> extends _i1.SmartFake implements _i5.Selectable<T> {
  _FakeSelectable_16(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeGenerationContext_17 extends _i1.SmartFake
    implements _i5.GenerationContext {
  _FakeGenerationContext_17(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeAppConfiguration_18 extends _i1.SmartFake
    implements _i8.AppConfiguration {
  _FakeAppConfiguration_18(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [AuthRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthRepository extends _i1.Mock implements _i9.AuthRepository {
  MockAuthRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i7.Future<_i2.Tenant> login(String? username, String? password) =>
      (super.noSuchMethod(
            Invocation.method(#login, [username, password]),
            returnValue: _i7.Future<_i2.Tenant>.value(
              _FakeTenant_0(
                this,
                Invocation.method(#login, [username, password]),
              ),
            ),
          )
          as _i7.Future<_i2.Tenant>);

  @override
  _i7.Future<void> logout() =>
      (super.noSuchMethod(
            Invocation.method(#logout, []),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<_i2.Tenant?> getCurrentTenant() =>
      (super.noSuchMethod(
            Invocation.method(#getCurrentTenant, []),
            returnValue: _i7.Future<_i2.Tenant?>.value(),
          )
          as _i7.Future<_i2.Tenant?>);
}

/// A class which mocks [ProductRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockProductRemoteDataSource extends _i1.Mock
    implements _i10.ProductRemoteDataSource {
  MockProductRemoteDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Client get client =>
      (super.noSuchMethod(
            Invocation.getter(#client),
            returnValue: _FakeClient_1(this, Invocation.getter(#client)),
          )
          as _i3.Client);

  @override
  _i7.Future<List<_i11.ProductModel>> fetchProducts({String? tenantId}) =>
      (super.noSuchMethod(
            Invocation.method(#fetchProducts, [], {#tenantId: tenantId}),
            returnValue: _i7.Future<List<_i11.ProductModel>>.value(
              <_i11.ProductModel>[],
            ),
          )
          as _i7.Future<List<_i11.ProductModel>>);

  @override
  _i7.Future<_i11.ProductModel?> getProductById(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getProductById, [id]),
            returnValue: _i7.Future<_i11.ProductModel?>.value(),
          )
          as _i7.Future<_i11.ProductModel?>);

  @override
  _i7.Future<void> addProduct(_i11.ProductModel? product) =>
      (super.noSuchMethod(
            Invocation.method(#addProduct, [product]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> updateProduct(_i11.ProductModel? product) =>
      (super.noSuchMethod(
            Invocation.method(#updateProduct, [product]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> deleteProduct(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteProduct, [id]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);
}

/// A class which mocks [SapProductDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockSapProductDataSource extends _i1.Mock
    implements _i12.SapProductDataSource {
  MockSapProductDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Client get client =>
      (super.noSuchMethod(
            Invocation.getter(#client),
            returnValue: _FakeClient_1(this, Invocation.getter(#client)),
          )
          as _i3.Client);

  @override
  _i7.Future<List<_i11.ProductModel>> fetchProducts({String? tenantId}) =>
      (super.noSuchMethod(
            Invocation.method(#fetchProducts, [], {#tenantId: tenantId}),
            returnValue: _i7.Future<List<_i11.ProductModel>>.value(
              <_i11.ProductModel>[],
            ),
          )
          as _i7.Future<List<_i11.ProductModel>>);

  @override
  _i7.Future<_i11.ProductModel?> getProductById(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getProductById, [id]),
            returnValue: _i7.Future<_i11.ProductModel?>.value(),
          )
          as _i7.Future<_i11.ProductModel?>);

  @override
  _i7.Future<void> addProduct(_i11.ProductModel? product) =>
      (super.noSuchMethod(
            Invocation.method(#addProduct, [product]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> updateProduct(_i11.ProductModel? product) =>
      (super.noSuchMethod(
            Invocation.method(#updateProduct, [product]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> deleteProduct(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteProduct, [id]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);
}

/// A class which mocks [ProductsDao].
///
/// See the documentation for Mockito's code generation for more information.
class MockProductsDao extends _i1.Mock implements _i13.ProductsDao {
  MockProductsDao() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.AppDatabase get db =>
      (super.noSuchMethod(
            Invocation.getter(#db),
            returnValue: _FakeAppDatabase_2(this, Invocation.getter(#db)),
          )
          as _i4.AppDatabase);

  @override
  _i4.AppDatabase get attachedDatabase =>
      (super.noSuchMethod(
            Invocation.getter(#attachedDatabase),
            returnValue: _FakeAppDatabase_2(
              this,
              Invocation.getter(#attachedDatabase),
            ),
          )
          as _i4.AppDatabase);

  @override
  _i5.DatabaseConnection get connection =>
      (super.noSuchMethod(
            Invocation.getter(#connection),
            returnValue: _FakeDatabaseConnection_3(
              this,
              Invocation.getter(#connection),
            ),
          )
          as _i5.DatabaseConnection);

  @override
  _i5.SqlTypes get typeMapping =>
      (super.noSuchMethod(
            Invocation.getter(#typeMapping),
            returnValue: _i14.dummyValue<_i5.SqlTypes>(
              this,
              Invocation.getter(#typeMapping),
            ),
          )
          as _i5.SqlTypes);

  @override
  _i5.DriftDatabaseOptions get options =>
      (super.noSuchMethod(
            Invocation.getter(#options),
            returnValue: _FakeDriftDatabaseOptions_4(
              this,
              Invocation.getter(#options),
            ),
          )
          as _i5.DriftDatabaseOptions);

  @override
  _i5.QueryExecutor get executor =>
      (super.noSuchMethod(
            Invocation.getter(#executor),
            returnValue: _FakeQueryExecutor_5(
              this,
              Invocation.getter(#executor),
            ),
          )
          as _i5.QueryExecutor);

  @override
  _i6.StreamQueryStore get streamQueries =>
      (super.noSuchMethod(
            Invocation.getter(#streamQueries),
            returnValue: _FakeStreamQueryStore_6(
              this,
              Invocation.getter(#streamQueries),
            ),
          )
          as _i6.StreamQueryStore);

  @override
  _i5.DatabaseConnectionUser get resolvedEngine =>
      (super.noSuchMethod(
            Invocation.getter(#resolvedEngine),
            returnValue: _FakeDatabaseConnectionUser_7(
              this,
              Invocation.getter(#resolvedEngine),
            ),
          )
          as _i5.DatabaseConnectionUser);

  @override
  _i4.$ProductsTable get products =>
      (super.noSuchMethod(
            Invocation.getter(#products),
            returnValue: _Fake$ProductsTable_8(
              this,
              Invocation.getter(#products),
            ),
          )
          as _i4.$ProductsTable);

  @override
  _i7.Future<List<_i4.Product>> getAllProducts({
    String? tenantId,
    String? branchId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getAllProducts, [], {
              #tenantId: tenantId,
              #branchId: branchId,
            }),
            returnValue: _i7.Future<List<_i4.Product>>.value(<_i4.Product>[]),
          )
          as _i7.Future<List<_i4.Product>>);

  @override
  _i7.Stream<List<_i4.Product>> watchAllProducts({
    String? tenantId,
    String? branchId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#watchAllProducts, [], {
              #tenantId: tenantId,
              #branchId: branchId,
            }),
            returnValue: _i7.Stream<List<_i4.Product>>.empty(),
          )
          as _i7.Stream<List<_i4.Product>>);

  @override
  _i7.Future<_i4.Product?> getProductById(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getProductById, [id]),
            returnValue: _i7.Future<_i4.Product?>.value(),
          )
          as _i7.Future<_i4.Product?>);

  @override
  _i7.Future<int> insertProduct(_i4.ProductsCompanion? product) =>
      (super.noSuchMethod(
            Invocation.method(#insertProduct, [product]),
            returnValue: _i7.Future<int>.value(0),
          )
          as _i7.Future<int>);

  @override
  _i7.Future<void> insertProducts(List<_i4.ProductsCompanion>? productsList) =>
      (super.noSuchMethod(
            Invocation.method(#insertProducts, [productsList]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<bool> updateProduct(_i4.ProductsCompanion? product) =>
      (super.noSuchMethod(
            Invocation.method(#updateProduct, [product]),
            returnValue: _i7.Future<bool>.value(false),
          )
          as _i7.Future<bool>);

  @override
  _i7.Future<int> deleteProduct(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteProduct, [id]),
            returnValue: _i7.Future<int>.value(0),
          )
          as _i7.Future<int>);

  @override
  _i7.Future<int> clearProducts() =>
      (super.noSuchMethod(
            Invocation.method(#clearProducts, []),
            returnValue: _i7.Future<int>.value(0),
          )
          as _i7.Future<int>);

  @override
  _i7.Stream<T> createStream<T extends Object>(
    _i6.QueryStreamFetcher<T>? stmt,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#createStream, [stmt]),
            returnValue: _i7.Stream<T>.empty(),
          )
          as _i7.Stream<T>);

  @override
  T alias<T, D>(_i5.ResultSetImplementation<T, D>? table, String? alias) =>
      (super.noSuchMethod(
            Invocation.method(#alias, [table, alias]),
            returnValue: _i14.dummyValue<T>(
              this,
              Invocation.method(#alias, [table, alias]),
            ),
          )
          as T);

  @override
  void markTablesUpdated(Iterable<_i5.TableInfo<_i5.Table, dynamic>>? tables) =>
      super.noSuchMethod(
        Invocation.method(#markTablesUpdated, [tables]),
        returnValueForMissingStub: null,
      );

  @override
  void notifyUpdates(Set<_i5.TableUpdate>? updates) => super.noSuchMethod(
    Invocation.method(#notifyUpdates, [updates]),
    returnValueForMissingStub: null,
  );

  @override
  _i7.Stream<Set<_i5.TableUpdate>> tableUpdates([
    _i5.TableUpdateQuery? query = const _i5.TableUpdateQuery.any(),
  ]) =>
      (super.noSuchMethod(
            Invocation.method(#tableUpdates, [query]),
            returnValue: _i7.Stream<Set<_i5.TableUpdate>>.empty(),
          )
          as _i7.Stream<Set<_i5.TableUpdate>>);

  @override
  _i7.Future<T> doWhenOpened<T>(
    _i7.FutureOr<T> Function(_i5.QueryExecutor)? fn,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#doWhenOpened, [fn]),
            returnValue:
                _i14.ifNotNull(
                  _i14.dummyValueOrNull<T>(
                    this,
                    Invocation.method(#doWhenOpened, [fn]),
                  ),
                  (T v) => _i7.Future<T>.value(v),
                ) ??
                _FakeFuture_9<T>(this, Invocation.method(#doWhenOpened, [fn])),
          )
          as _i7.Future<T>);

  @override
  _i5.InsertStatement<T, D> into<T extends _i5.Table, D>(
    _i5.TableInfo<T, D>? table,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#into, [table]),
            returnValue: _FakeInsertStatement_10<T, D>(
              this,
              Invocation.method(#into, [table]),
            ),
          )
          as _i5.InsertStatement<T, D>);

  @override
  _i5.UpdateStatement<Tbl, R> update<Tbl extends _i5.Table, R>(
    _i5.TableInfo<Tbl, R>? table,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#update, [table]),
            returnValue: _FakeUpdateStatement_11<Tbl, R>(
              this,
              Invocation.method(#update, [table]),
            ),
          )
          as _i5.UpdateStatement<Tbl, R>);

  @override
  _i5.SimpleSelectStatement<T, R> select<T extends _i5.HasResultSet, R>(
    _i5.ResultSetImplementation<T, R>? table, {
    bool? distinct = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#select, [table], {#distinct: distinct}),
            returnValue: _FakeSimpleSelectStatement_12<T, R>(
              this,
              Invocation.method(#select, [table], {#distinct: distinct}),
            ),
          )
          as _i5.SimpleSelectStatement<T, R>);

  @override
  _i5.JoinedSelectStatement<T, R> selectOnly<T extends _i5.HasResultSet, R>(
    _i5.ResultSetImplementation<T, R>? table, {
    bool? distinct = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#selectOnly, [table], {#distinct: distinct}),
            returnValue: _FakeJoinedSelectStatement_13<T, R>(
              this,
              Invocation.method(#selectOnly, [table], {#distinct: distinct}),
            ),
          )
          as _i5.JoinedSelectStatement<T, R>);

  @override
  _i5.BaseSelectStatement<_i5.TypedResult> selectExpressions(
    Iterable<_i5.Expression<Object>>? columns,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#selectExpressions, [columns]),
            returnValue: _FakeBaseSelectStatement_14<_i5.TypedResult>(
              this,
              Invocation.method(#selectExpressions, [columns]),
            ),
          )
          as _i5.BaseSelectStatement<_i5.TypedResult>);

  @override
  _i5.DeleteStatement<T, D> delete<T extends _i5.Table, D>(
    _i5.TableInfo<T, D>? table,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#delete, [table]),
            returnValue: _FakeDeleteStatement_15<T, D>(
              this,
              Invocation.method(#delete, [table]),
            ),
          )
          as _i5.DeleteStatement<T, D>);

  @override
  _i7.Future<int> customUpdate(
    String? query, {
    List<_i5.Variable<Object>>? variables = const [],
    Set<_i5.ResultSetImplementation<dynamic, dynamic>>? updates,
    _i5.UpdateKind? updateKind,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #customUpdate,
              [query],
              {
                #variables: variables,
                #updates: updates,
                #updateKind: updateKind,
              },
            ),
            returnValue: _i7.Future<int>.value(0),
          )
          as _i7.Future<int>);

  @override
  _i7.Future<int> customInsert(
    String? query, {
    List<_i5.Variable<Object>>? variables = const [],
    Set<_i5.ResultSetImplementation<dynamic, dynamic>>? updates,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #customInsert,
              [query],
              {#variables: variables, #updates: updates},
            ),
            returnValue: _i7.Future<int>.value(0),
          )
          as _i7.Future<int>);

  @override
  _i7.Future<List<_i5.QueryRow>> customWriteReturning(
    String? query, {
    List<_i5.Variable<Object>>? variables = const [],
    Set<_i5.ResultSetImplementation<dynamic, dynamic>>? updates,
    _i5.UpdateKind? updateKind,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #customWriteReturning,
              [query],
              {
                #variables: variables,
                #updates: updates,
                #updateKind: updateKind,
              },
            ),
            returnValue: _i7.Future<List<_i5.QueryRow>>.value(<_i5.QueryRow>[]),
          )
          as _i7.Future<List<_i5.QueryRow>>);

  @override
  _i5.Selectable<_i5.QueryRow> customSelect(
    String? query, {
    List<_i5.Variable<Object>>? variables = const [],
    Set<_i5.ResultSetImplementation<dynamic, dynamic>>? readsFrom = const {},
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #customSelect,
              [query],
              {#variables: variables, #readsFrom: readsFrom},
            ),
            returnValue: _FakeSelectable_16<_i5.QueryRow>(
              this,
              Invocation.method(
                #customSelect,
                [query],
                {#variables: variables, #readsFrom: readsFrom},
              ),
            ),
          )
          as _i5.Selectable<_i5.QueryRow>);

  @override
  _i5.Selectable<_i5.QueryRow> customSelectQuery(
    String? query, {
    List<_i5.Variable<Object>>? variables = const [],
    Set<_i5.ResultSetImplementation<dynamic, dynamic>>? readsFrom = const {},
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #customSelectQuery,
              [query],
              {#variables: variables, #readsFrom: readsFrom},
            ),
            returnValue: _FakeSelectable_16<_i5.QueryRow>(
              this,
              Invocation.method(
                #customSelectQuery,
                [query],
                {#variables: variables, #readsFrom: readsFrom},
              ),
            ),
          )
          as _i5.Selectable<_i5.QueryRow>);

  @override
  _i7.Future<void> customStatement(String? statement, [List<dynamic>? args]) =>
      (super.noSuchMethod(
            Invocation.method(#customStatement, [statement, args]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<T> transaction<T>(
    _i7.Future<T> Function()? action, {
    bool? requireNew = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #transaction,
              [action],
              {#requireNew: requireNew},
            ),
            returnValue:
                _i14.ifNotNull(
                  _i14.dummyValueOrNull<T>(
                    this,
                    Invocation.method(
                      #transaction,
                      [action],
                      {#requireNew: requireNew},
                    ),
                  ),
                  (T v) => _i7.Future<T>.value(v),
                ) ??
                _FakeFuture_9<T>(
                  this,
                  Invocation.method(
                    #transaction,
                    [action],
                    {#requireNew: requireNew},
                  ),
                ),
          )
          as _i7.Future<T>);

  @override
  _i7.Future<T> exclusively<T>(_i7.Future<T> Function()? action) =>
      (super.noSuchMethod(
            Invocation.method(#exclusively, [action]),
            returnValue:
                _i14.ifNotNull(
                  _i14.dummyValueOrNull<T>(
                    this,
                    Invocation.method(#exclusively, [action]),
                  ),
                  (T v) => _i7.Future<T>.value(v),
                ) ??
                _FakeFuture_9<T>(
                  this,
                  Invocation.method(#exclusively, [action]),
                ),
          )
          as _i7.Future<T>);

  @override
  _i7.Future<void> batch(_i7.FutureOr<void> Function(_i5.Batch)? runInBatch) =>
      (super.noSuchMethod(
            Invocation.method(#batch, [runInBatch]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<T> runWithInterceptor<T>(
    _i7.Future<T> Function()? action, {
    required _i5.QueryInterceptor? interceptor,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #runWithInterceptor,
              [action],
              {#interceptor: interceptor},
            ),
            returnValue:
                _i14.ifNotNull(
                  _i14.dummyValueOrNull<T>(
                    this,
                    Invocation.method(
                      #runWithInterceptor,
                      [action],
                      {#interceptor: interceptor},
                    ),
                  ),
                  (T v) => _i7.Future<T>.value(v),
                ) ??
                _FakeFuture_9<T>(
                  this,
                  Invocation.method(
                    #runWithInterceptor,
                    [action],
                    {#interceptor: interceptor},
                  ),
                ),
          )
          as _i7.Future<T>);

  @override
  _i5.GenerationContext $write(
    _i5.Component? component, {
    bool? hasMultipleTables,
    int? startIndex,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #$write,
              [component],
              {#hasMultipleTables: hasMultipleTables, #startIndex: startIndex},
            ),
            returnValue: _FakeGenerationContext_17(
              this,
              Invocation.method(
                #$write,
                [component],
                {
                  #hasMultipleTables: hasMultipleTables,
                  #startIndex: startIndex,
                },
              ),
            ),
          )
          as _i5.GenerationContext);

  @override
  _i5.GenerationContext $writeInsertable(
    _i5.TableInfo<_i5.Table, dynamic>? table,
    _i5.Insertable<dynamic>? insertable, {
    int? startIndex,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #$writeInsertable,
              [table, insertable],
              {#startIndex: startIndex},
            ),
            returnValue: _FakeGenerationContext_17(
              this,
              Invocation.method(
                #$writeInsertable,
                [table, insertable],
                {#startIndex: startIndex},
              ),
            ),
          )
          as _i5.GenerationContext);

  @override
  String $expandVar(int? start, int? amount) =>
      (super.noSuchMethod(
            Invocation.method(#$expandVar, [start, amount]),
            returnValue: _i14.dummyValue<String>(
              this,
              Invocation.method(#$expandVar, [start, amount]),
            ),
          )
          as String);

  @override
  _i7.Future<void> close() =>
      (super.noSuchMethod(
            Invocation.method(#close, []),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);
}

/// A class which mocks [ConfigurationRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockConfigurationRepository extends _i1.Mock
    implements _i15.ConfigurationRepository {
  MockConfigurationRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i7.Future<_i8.AppConfiguration> getConfiguration() =>
      (super.noSuchMethod(
            Invocation.method(#getConfiguration, []),
            returnValue: _i7.Future<_i8.AppConfiguration>.value(
              _FakeAppConfiguration_18(
                this,
                Invocation.method(#getConfiguration, []),
              ),
            ),
          )
          as _i7.Future<_i8.AppConfiguration>);

  @override
  _i7.Future<void> saveConfiguration(_i8.AppConfiguration? configuration) =>
      (super.noSuchMethod(
            Invocation.method(#saveConfiguration, [configuration]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);
}
