// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBTNdlD_F8mtCwEV0Wmq8GHkt-wSakVWYk',
    appId: '1:876840743697:web:5c99c112e1f102f5e612b0',
    messagingSenderId: '876840743697',
    projectId: 'kflkiosk-dc264',
    authDomain: 'kflkiosk-dc264.firebaseapp.com',
    storageBucket: 'kflkiosk-dc264.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAKwtibcBxrFM7Zya2ICj1_J6cNK9uc0gg',
    appId: '1:876840743697:android:1a1aca7177542bcde612b0',
    messagingSenderId: '876840743697',
    projectId: 'kflkiosk-dc264',
    storageBucket: 'kflkiosk-dc264.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBUNK45LNs6Rq8sUVnMnVZVSm5CHgD0qsw',
    appId: '1:876840743697:ios:fc916d0ff50ad7e0e612b0',
    messagingSenderId: '876840743697',
    projectId: 'kflkiosk-dc264',
    storageBucket: 'kflkiosk-dc264.firebasestorage.app',
    iosBundleId: 'com.example.kflkiosk',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBUNK45LNs6Rq8sUVnMnVZVSm5CHgD0qsw',
    appId: '1:876840743697:ios:fc916d0ff50ad7e0e612b0',
    messagingSenderId: '876840743697',
    projectId: 'kflkiosk-dc264',
    storageBucket: 'kflkiosk-dc264.firebasestorage.app',
    iosBundleId: 'com.example.kflkiosk',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBTNdlD_F8mtCwEV0Wmq8GHkt-wSakVWYk',
    appId: '1:876840743697:web:a44fc26dd3daffeee612b0',
    messagingSenderId: '876840743697',
    projectId: 'kflkiosk-dc264',
    authDomain: 'kflkiosk-dc264.firebaseapp.com',
    storageBucket: 'kflkiosk-dc264.firebasestorage.app',
  );
}
